input_data_path: 'data/raw/data.csv'
output_model_path: 'models/store/lr_model.pkl'
metric_path: 'models/store/lr_metrics.json'

splitting_params:
  val_size: 0.33
  random_state: 42

train_params:
  model_type: 'LogisticRegression'
  options:
    random_state: 42

feature_params:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'
  numeric_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  target_col: 'condition'
