apiVersion: v1
kind: Pod
metadata:
  name: online-inference
  labels:
    app: online-inference
spec:
  containers:
    - image: agorlenko/online_inference:v2
      name: online-inference
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "128Mi"
          cpu: "1"
        limits:
          memory: "256Mi"
          cpu: "2"
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 20
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 20
        periodSeconds: 10
