apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: online-inference
  labels:
    app: online-inference
spec:
  replicas: 8
  selector:
    matchLabels:
      app: online-inference
  template:
    metadata:
      name: online-inference
      labels:
        app: online-inference
    spec:
      containers:
        - image: agorlenko/online_inference:v1
          name: online-inference
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "1"
            limits:
              memory: "256Mi"
              cpu: "2"
