apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-inference
  labels:
    app: online-inference
spec:
  replicas: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
      maxUnavailable: 0
  selector:
    matchLabels:
      app: online-inference
  template:
    metadata:
      name: online-inference
      labels:
        app: online-inference
    spec:
      containers:
        - image: agorlenko/online_inference:v2
          name: online-inference
          ports:
            - containerPort: 8000
